"""create user_models table

Revision ID: 2ece506ada19
Revises: 
Create Date: 2025-01-09 15:42:07.611439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ece506ada19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chords')
    op.drop_table('songs')
    op.drop_table('course_lessons')
    op.drop_table('lesson_keys')
    op.drop_table('keys')
    op.drop_table('lessons')
    op.drop_table('courses')
    op.drop_table('progressions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('progression_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('progression_name')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('details_of_course', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('details_of_course')
    )
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pulls_to', sa.VARCHAR(length=100), nullable=False),
    sa.Column('pulls_from', sa.VARCHAR(length=40), nullable=False),
    sa.Column('songs', sa.VARCHAR(length=40), nullable=False),
    sa.Column('chords', sa.VARCHAR(length=40), nullable=False),
    sa.Column('progressions', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_table('lesson_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('song', sa.VARCHAR(length=100), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=40), nullable=False),
    sa.Column('chords_used', sa.VARCHAR(length=40), nullable=False),
    sa.Column('progression_used', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chord_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chord_name')
    )
    # ### end Alembic commands ###
